language: cpp
sudo: required
dist: trusty
env:
  global:
    - secure: "LzLVM/dN1L/MCqBrU3oWXFg86L6denRTcH+CdxOZWu5Y5PxWTzmfxYvPQS+C7EsVp8cuaS54vPy39HihJIYG5wmBBZxRhq3pNSJt25+dxx4Qe/WXooxlkCQ6JKhJB8vBCHEFPFd5CKlZOd6QacauS18KAQNZx+D/wWtT+f19Mata+C/POGbIa4+JQ9imwSPDJg+wpTSbgjfvuf/UyQFMXIXI83fjFx90+c18iLjv8b0xyCvIieIxjFR5wyZCeoXvlQYLkmObxdFedQaiTzo5EJZwsYzfKfF1ltGf45/olMVsSjI/tOOGxmprCk2tS2q1GVd/H+Cz27SqgXJIRSUogCa0r3mSfQ8+SpiM1du6OEYf823/WpOO8H6VrokRmdnjvizBicjYVs93MSFWm73LVbRsHncBQvqKw4J1VEPQRlluCOwg+yFbHFFyH6wdtIvAfxvekVym717WlmDk9wmrielPRQ6YfQKp4nRkuu4bgWTO27vVo1MRdet7DaNOuqyoYRRfoINkL8LiHh1lM1DUdIVKMP1M0r1lzZVKritw45/GoLTfx1k2Muz/gCg9QczQmXnyX8CnsTtengNDcFfuQ2TeP77YqtGN1ewlpG8jYq5DZOvzOEzJCRxUyqlPCNEanpJXQkmRzMPsy0c6P2Ac7GIo4/Wmk+YHrvbCdCrtLtU="
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - libboost-dev
      - libboost-date-time-dev
      - libboost-regex-dev
      - libboost-system-dev
      - libboost-filesystem-dev
      - build-essential
      - liblua5.1-0-dev
      - python-virtualenv
      - python-bottle
      - libgeoip-dev
      - geoip-database
      - cpanminus
      - libprotobuf-dev
      - protobuf-compiler
      - libhiredis-dev
      - libcurl4-openssl-dev
      - redis-server
      - libyaml-cpp-dev
      - wget
script:
 - autoreconf -i
 - ./configure --enable-docker
 - cd docker
 - make regression-gcc
 - make regression-clang
 - cd ..
 - git submodule init
 - git submodule update
 - builder/build.sh debian-stretch
 - builder/build.sh centos-7
 - ./trigger_policy_build.sh
notifications:
  irc:
    channels:
      - "irc.oftc.net#dovepower"
    template:
      - "%{author} @ %{repository} / %{branch} - Build:#%{build_number} : %{message} - Changes: %{compare_url} - Build details: %{build_url}"
    use_notice: true
    skip_join: true
