version: '2'
services:
  logstash:
    build: logstash
    ports:
      - "4501:4501/udp"
      - "8080:8080/tcp"
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
      - ./logstash/templates:/tmp/templates
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
  elasticsearch:
    build: elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
  regression:
    cap_add:
      - ALL
    security_opt:
      - seccomp=unconfined
    build:
      context: weakforced
      dockerfile: docker/regression/Dockerfile
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    links:
      - elasticsearch
      - logstash
    depends_on:
      - elasticsearch
      - logstash
volumes:
  esdata:
    driver: local
