version: '2'
services:
  logstash:
    build: logstash
    ports:
      - "4501:4501/udp"
      - "8080:8080/tcp"
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
      - ./logstash/geoip:/usr/share/logstash/geoip
      - ./logstash/templates:/tmp/templates
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - docker_elk
  elasticsearch:
    build: elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - docker_elk
  regression:
    build:
      context: ..
      dockerfile: docker/regression/Dockerfile
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    links:
      - elasticsearch
      - logstash
    depends_on:
      - elasticsearch
      - logstash
    networks:
      - docker_elk

networks:
  docker_elk:
    driver: bridge
volumes:
  esdata:
    driver: local
